clc;
close all;
clear all;
t=0:1:100;
x=sin(2*pi*0.05*t);
subplot(2,1,1);
plot(t,x);
title('Sinusoidal signal');
grid on;
y=xcorr(x);
t1=t;
t2=-fliplr(t);
n1=min(t1)+min(t2);
n2=max(t1)+max(t2);
n=n1:1:n2;
subplot(2,1,2);
plot(n,y);
title('Autocorrelation function of sine wave');
grid on;